msh_file: data/short_caterpillar.msh
scad_file: data/caterpillar.scad
scad_parameters: data/short_caterpillar_unequal_scad_params.json
ideal_edge_length: 0.02
robot_density: 1080.0
robot_youngs_modulus: 149000
robot_poissons_ratio: 0.45
robot_damping_factor: 0.4
robot_frozen_bounding_box:
- -.inf
- -0.01
- -.inf
- .inf
- .inf
- .inf
robot_translation:
- 0.0
- 0.0
- 0.0
robot_rotation_vector:
- 1.0
- 0.0
- 0.0
robot_rotation_degrees: 90.0
robot_scale:
- 0.001
- 0.001
- 0.001
cable_pull_ratio:
- 7.3554e-02
- 1.0971e-01
- 7.8925e-01
cable_stiffness: 100
cable_damping: 0.01
object_file: data/sphere.obj
object_density: 1080.0
object_translation:
- -8.26
- -38.56
- 11.46
object_rotation_vector:
- 0.0
- 0.0
- 1.0
object_rotation_degrees: 0.0
object_scale:
- 0.005
- 0.005
- 0.005
sim_duration: 1.0
sim_segment_duration: 0.1
sim_dt: 5.0e-05
contact_distance: 0.0
contact_ke: 0.1
contact_kd: 0.1
contact_kf: 0.1
ground: false
learning_rate: 1.0
num_training_iterations: 200
device: cuda
use_checkpoint: true
out_path: .dev/point_touch
obstacle_file:
- tests/data/cylinder.obj
- tests/data/cylinder.obj
obstacle_density:
- 1080.0
- 1080.0
obstacle_translation:
- - 5.0
  - -35
  - -85.0
- - -30.0
  - -120.0
  - -80.0
obstacle_rotation_vector:
- - 0
  - 1
  - 0
- - 0
  - 1
  - 0
obstacle_rotation_degrees:
- 120
- 120
obstacle_scale:
- - 0.001
  - 0.001
  - 0.001
- - 0.001
  - 0.001
  - 0.001
